version: 2.1

orbs:
  node: circleci/node@4.1.0

jobs:
  install_dependencies:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: LeslieProject
      - run:
          name: Clean npm cache, Remove node_modules and package-lock.json and Reinstall
          command: |
            cd LeslieProject
            npm cache clean --force
            rm -rf node_modules package-lock.json
            npm install || (cat /home/circleci/.npm/_logs/*-debug.log && exit 1)
      - run:
          name: Install specific package
          command: |
            cd LeslieProject
            npm install @react-native-community/datetimepicker || (cat /home/circleci/.npm/_logs/*-debug.log && exit 1)

  build_android:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: LeslieProject
      - run:
          name: Install eas-cli
          command: npm install -g eas-cli
      - run:
          name: EAS Login
          command: echo "$EXPO_CLI_PASSWORD" | eas login --non-interactive --username=$EXPO_CLI_USERNAME
      - run:
          name: Build Android
          command: eas build --platform android
      - run:
          name: Get Build URL
          command: echo "Check the build at $(eas build:url $(eas build:list --json | jq -r '.data[0].id'))"

workflows:
  version: 2
  build:
    jobs:
      - install_dependencies
      - build_android:
          requires:
            - install_dependencies
